version: "3"  
services:  
  nginx:
    image: nginx:latest
    container_name: nginx_airport
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - ./nginx:/etc/nginx/conf.d
      - ./timezone:/etc/timezone
    depends_on:
      - web
  rabbit:
      image: rabbitmq:latest
      environment:
          - RABBITMQ_DEFAULT_USER=admin
          - RABBITMQ_DEFAULT_PASS=asdasdasd
      ports:
          - "5672:5672"
          - "15672:15672"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/start_web.sh
    container_name: django_airport
    volumes:
      - ./:/app
      - ./timezone:/etc/timezone
    expose:
      - "8080"
    links:
        - rabbit
    depends_on:
        - rabbit
  celerybeat:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/start_celerybeat.sh
    volumes:
      - ./:/app
      - ./timezone:/etc/timezone
    links:
      - rabbit
      - web
    depends_on:
      - celeryd
      - rabbit
      - web
  celeryd:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/start_celeryd.sh
    volumes:
      - ./:/app
      - ./timezone:/etc/timezone
    links:
      - rabbit
      - web
    depends_on:
      - rabbit
      - web