version: "3"  
services:
  nginx:
    container_name: nginx_airport
    depends_on:
      - web
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./:/home/airport/mount_point/
      - ./nginx_configuration/docker_nginx_configuration:/etc/nginx/conf.d
      - ./timezone:/etc/timezone
  rabbit:
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=asdasdasd
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: /home/airport/mount_point/start_web.sh
    container_name: django_airport
    expose:
      - "8080"
    volumes:
      - ./:/home/airport/mount_point/
      - ./timezone:/etc/timezone
  celerybeat:
    build:
      context: ./
      dockerfile: Dockerfile
    command: /home/airport/mount_point/start_celerybeat.sh
    depends_on:
      - celeryd
      - web
    volumes:
      - ./:/home/airport/mount_point/
      - ./timezone:/etc/timezone
  celeryd:
    build:
      context: ./
      dockerfile: Dockerfile
    command: /home/airport/mount_point/start_celeryd.sh
    depends_on:
      - rabbit
      - web
    volumes:
      - ./:/home/airport/mount_point/
      - ./timezone:/etc/timezone