# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirTrafficController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=20)),
                ('flight_code', models.CharField(max_length=10)),
                ('sch_departure_datetime', models.DateTimeField(blank=True)),
                ('day', models.CharField(max_length=9)),
                ('airport', models.CharField(max_length=3)),
                ('proper_atc', models.BooleanField(default=False)),
                ('sch_arrival_local_datetime', models.DateTimeField(blank=True)),
                ('real_arrival_local_datetime', models.DateTimeField(blank=True, null=True)),
                ('online_atc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_online_atc', to='airport_management.AirTrafficController')),
                ('past_atcs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_past_atcs', to='airport_management.AirTrafficController')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=20)),
                ('flight_code', models.CharField(max_length=10)),
                ('sch_departure_datetime', models.DateTimeField(blank=True)),
                ('day', models.CharField(max_length=9)),
                ('airport', models.CharField(max_length=3)),
                ('proper_atc', models.BooleanField(default=False)),
                ('online_atc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_online_atc', to='airport_management.AirTrafficController')),
                ('past_atcs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_past_atcs', to='airport_management.AirTrafficController')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='airtrafficcontroller',
            name='past_flights_arrival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airport_management.Arrival'),
        ),
        migrations.AddField(
            model_name='airtrafficcontroller',
            name='past_flights_departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airport_management.Departure'),
        ),
    ]
