# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_api_pull_is_on_going', models.BooleanField(default=False)),
                ('backup_to_fixture_is_on_going', models.BooleanField(default=False)),
                ('need_backup_to_fixtures', models.BooleanField(default=False)),
            ],
        ),
    ]
