# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_management', '0002_celeryworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeryworker',
            name='check_this_minute_flights_status',
            field=models.BooleanField(default=False),
        ),
    ]
